version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bexup-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
    - .volumes/MongoDB:/data/db
    networks:
      - bexup-network

  # api:
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - bexup-network

  # consumer:
  #   networks:
  #     - bexup-network

networks:
  bexup-network:

volumes:
  logs:
