version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bexup-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
    - .volumes/MongoDB:/data/db
    networks:
      - bexup-network

  api:
    build:
     ./api
    ports:
      - "8000:8000"
    environment:
      MONGO_DB_URL: ${MONGO_DB_URL}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_DB_COLLECTION: ${MONGO_DB_COLLECTION}
      MESSAGE_BROKER_URL: ${MESSAGE_BROKER_URL}
      CAR_QUEUE_NAME: ${CAR_QUEUE_NAME}
      TRUCK_QUEUE_NAME: ${TRUCK_QUEUE_NAME}
      MOTORCYCLE_QUEUE_NAME: ${MOTORCYCLE_QUEUE_NAME}
    networks:
      - bexup-network

  consumer:
    build:
     ./consumer
    environment:
      MONGO_DB_URL: ${MONGO_DB_URL}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_DB_COLLECTION: ${MONGO_DB_COLLECTION}
      MESSAGE_BROKER_URL: ${MESSAGE_BROKER_URL}
      CAR_QUEUE_NAME: ${CAR_QUEUE_NAME}
      TRUCK_QUEUE_NAME: ${TRUCK_QUEUE_NAME}
      MOTORCYCLE_QUEUE_NAME: ${MOTORCYCLE_QUEUE_NAME}
    networks:
      - bexup-network

networks:
  bexup-network:

volumes:
  logs:
